### ISSUE TITLE
Cannot make vscode to recognize the module through pip install

### ISSUE THREAD

**Issue by leandrorojas** [sinch/python-sinch-sms#2]
Using:
- macOS Mojave 10.14.6 (18G9323)
- Python 3.7.7
- vscode 1.63.2

what I did:
- On my terminal: pip install sinchSMS
- created a new file in my project and used "from sinchsms import sinchSMS"
- I get "Import "sinchsms" could not be resolved by Pylance"

**Comment by Deepanshdevelop0** [comment]
use git clone "repo_link"
